branches:
  only:
    - master

language: go

sudo: false

go:
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

notifications:
  email: false

before_script:
  - go get golang.org/x/lint/golint

script:
  - sh ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
